name = "vaultbridge"
main = "bridge.js"
compatibility_date = "2025-04-22"

[env.production]
routes = ["https://faa.zone/bridge"]

[env.production.vars]
SECRET_OPENAI_KEY = "sk-proj-..."  # (your real key goes here)

[observability.logs]
enabled = true
