name = "vaultbridge"
type = "javascript"
account_id = "ad41fcfe1a84b27c62cc5cc9d590720e"  # ✅ From your dashboard
workers_dev = true

[vars]
SECRET_OPENAI_KEY = "${OPENAI_API_KEY}"
VAULT_API_PROXY = "${VAULT_API_PROXY}"

